# Config file for air live reload
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/newsletter ./app"
  bin = "tmp/newsletter"
  include_ext = ["go"]
  exclude_dir = ["tmp"]
  follow_symlink = true
  stop_on_error = true

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
