version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  app:
    build: .
    env_file: .env
    depends_on:
      - db
    ports:
      - "3000:3000"

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./docs/openapi.yaml:/usr/share/nginx/html/openapi.yaml:ro
    environment:
      SWAGGER_JSON: /usr/share/nginx/html/openapi.yaml