services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    networks:
      - newsletter-go-network

  app-prod:
    image: 590183723398.dkr.ecr.eu-central-1.amazonaws.com/newsletter-go:latest
    depends_on:
      - db
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - newsletter-go-network

networks:
  newsletter-go-network:
    driver: bridge

