services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    networks:
      - newsletter-go-network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrations:
    image: 590183723398.dkr.ecr.eu-central-1.amazonaws.com/newsletter-go:latest
    command: sh -c "go install github.com/pressly/goose/v3/cmd/goose@latest && goose -dir db/migrations postgres \"postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable\" up"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres

  app-prod:
    image: 590183723398.dkr.ecr.eu-central-1.amazonaws.com/newsletter-go:latest
    depends_on:
      - db
      - migrations
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - newsletter-go-network

networks:
  newsletter-go-network:
    driver: bridge

volumes:
  postgres_data:
