version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  app-prod:
#    build: .
#    env_file: .env
#   depends_on:
#      - db
#    ports:
#      - "3000:3000"

  app-dev:
    image: cosmtrek/air
    working_dir: /app
    env_file: .env
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./:/app

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./docs/openapi.yaml:/openapi.yaml:ro
    environment:
      SWAGGER_JSON: /openapi.yaml

volumes:
  postgres_data:
